spring:
  application:
    name: spring-ai-docling
  autoconfigure:
    exclude:
      - org.springframework.ai.mcp.client.httpclient.autoconfigure.StreamableHttpHttpClientTransportAutoConfiguration
  ai:
    mcp:
      client:
        type: SYNC
        initialized: false
        streamable-http:
          connections:
            docling:
              url: http://localhost:8000
              endpoint: /mcp
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-5.1
#        stdio:
#          servers-configuration: classpath:mcp-servers.json

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    io.modelcontextprotocol.client.transport: INFO
    io.modelcontextprotocol: DEBUG
    reactor.netty.http.client: DEBUG
    org.springframework.web.reactive.function.client.ExchangeFunctions: TRACE
    org.springframework.ai.chat: DEBUG
    org.springframework.ai.chat.client: DEBUG
    org.springframework.ai.ollama: DEBUG
    org.springframework.ai.mcp: DEBUG
    org.springframework.ai.chat.model: TRACE

    org.rag4j.docling.spring_ai_docling: DEBUG
